### ISSUE TITLE
Sessions never expire

### ISSUE THREAD

**Issue by pronebird** [donpark/session-mongoose#10]
Recently I found my DB full of sessions. What seems strange is that "expires" field always set to NULL for each document in db. Seems like that's why those records never get expired, e.g. removed. I use interval set to 120000.

**Comment by donpark** [comment]
Are you setting cookie.maxAge in session configuration? I left out that part in the README doc but added it just now since without maxAge set sessions will not expire. See below:

```
// configure session provider
app.use(express.session({
    store: store,
    cookie: { maxAge: 900000 } // expire session in 15 min or 900 seconds
});
```

I also added code to use maxAge to calculate expires when expires is missing (like in direct version of unit test).

If you set maxAge, last published version should start expiring sessions. Updated version hasn't been published yet because NPM registry server is having issues.

**Comment by pronebird** [comment]
so maxAge and interval should be the same? I don't setup maxAge :/

**Comment by donpark** [comment]
> so maxAge and interval should be the same? I don't setup maxAge :/

No. `maxAge` is how long (in milliseconds) you want your session to last.

`interval` is how often you (in milliseconds) you want expiration timestamp checking to occur.

So if `maxAge` is 900000 and `interval` is 120000 then your session will expire in 15min to 17min.

**Comment by pronebird** [comment]
aha so basically interval used to "garbage collect" sessions while maxAge used to define the real session lifetime. am I right? Thanks a lot for explanation.

**Comment by donpark** [comment]
Correct. Session may expire logically but it's not physically expired (removed from DB) unless the "garbage collector" runs. Please close this issue after confirming that specifying `maxAge` fixes your problem. Thanks.

**Comment by pronebird** [comment]
Worth to mention, maxAge by default is 4 hours (http://www.senchalabs.org/connect/middleware-session.html), not exactly sure why session-mongoose gets confused then.

**Comment by donpark** [comment]
That's what the doc said but it's no longer reflected in the code. I suspect the change happened in last major version upgrade.
