### ISSUE TITLE
Use an existing connection

### ISSUE THREAD

**Issue by taxilian** [donpark/session-mongoose#9]
Great project! We may end up using it.  One quick thing, though, is that it would be really helpful for many projects if the session store could use an existing mongoose connection instead of creating its own. We don't really want to create a database that is only used for session data....

if we adopt this for use at GradeCam we may implement it ourselves, but I thought I'd drop the suggestion in.

**Comment by donpark** [comment]
Separate connection is used simply because I've assumed the way I deploy is the way most people would given that access profile for session storage is different from normal MongoDB application's access pattern which calls for similar differences in MongoDB configuration. Still adding this as an optional feature makes sense.

I am not sure when and if this feature will be added but thx for the suggestion @taxilian.

**Comment by donpark** [comment]
@taxilian version 0.2.2 includes custom connection support code contributed by @pronebird.

Please see example in README.
